name: SonarQube Embarcadero Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 분석 정확도를 위해 shallow clone 비활성화

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Set Embarcadero Environment
        run: |
          "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\rsvars.bat"
        shell: cmd

      - name: Install SonarQube Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5

      - name: Run Build with Wrapper
        run: |
          build-wrapper-win-x86-64.exe --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} ^
          msbuild MyProject.cbproj /p:Platform=Win32 /p:Config=Release
        shell: cmd

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
